theme: jekyll-theme-minimal
title: ğŸ“
description: |
  ğŸ  Dakar, SÃ©nÃ©gal
  <br/>
  <a href="mailto:diamasta@gmail.com">ğŸ“§ diamasta@gmail.com</a>
  <br/>
  <a href="https://github.com/massire1">ğŸ‘¨ğŸ¾â€ğŸ’» Github</a>
  <br/>
  <a href="https://www.linkedin.com/in/massire-dia/">ğŸ–‡ï¸ LinkedIn</a>
  <br/>
